### ISSUE TITLE
Document setup of local jupyter notebooks

### ISSUE THREAD

**Issue by adampingel** [ibm-granite-cookbooks/pm#87]

**Comment by fayvor** [comment]
Looks like the PR was closed. Recreating...

**Comment by deanwampler** [comment]
I recommend pip-installing `jupyterlab` rather than `notebook`, because you get a nicer experience. You can run one server (`jupyter lab`) and then navigate to any of the notebooks you want.

https://jupyter.org/install

**Comment by fayvor** [comment]
@deanwampler I agree that jupyterlab is nice, but I'd like to provide an easy command-line instruction.

If I `pip install jupyterlab` (rather than `pip install notebook`) and try to open a notebook, I get this:
```
(.venv) fayvor@MacBook-Pro test % jupyter notebook Text_to_Shell.ipynb
...
Jupyter command `jupyter-notebook` not found.
```

Does this work for you? If not, do you know the command for opening a notebook from the command line with jupyterlab?

**Comment by fayvor** [comment]
[Resubmitted the PR.](https://github.com/ibm-granite-community/granite-code-cookbook/pull/42)

**Comment by fayvor** [comment]
@deanwampler I think I'll just tack on a section for jupyterlab at the end of the notebook.

**Comment by deanwampler** [comment]
Done
